# Generated by Django 3.0.5 on 2020-07-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otomasiACL', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
