# Generated by Django 3.0.5 on 2020-07-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otomasiACL', '0002_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ip', models.CharField(max_length=100, verbose_name='Alamat IP')),
            ],
        ),
    ]
