# Generated by Django 3.0.5 on 2020-07-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otomasiACL', '0003_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='acl',
            field=models.CharField(default='', max_length=255, verbose_name='Konfigurasi Access-List'),
        ),
    ]
